import type { Metadata } from "next";
import "./globals.css";
import MenuList from "./admin/menuList";
import ManagerTemplate from "@/components/managerTemplate";

export const metadata: Metadata = {
  title: "Zenith",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ManagerTemplate title="Dashboard" id="dashboard" menuList={MenuList}>
          {children}
        </ManagerTemplate>
      </body>
    </html>
  );
}